# Form implementation generated from reading ui file 'CrearEncuesta.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from xml.dom import NoModificationAllowedErr
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CrearEncuesta(object):
    def setupUi(self, MisEncuestas, datos: tuple | None):
        MisEncuestas.setObjectName("MisEncuestas")
        MisEncuestas.resize(708, 866)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/editar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        
        MisEncuestas.setWindowIcon(icon)
        
        self.label_titulo_encuesta = QtWidgets.QLabel(MisEncuestas)
        self.label_titulo_encuesta.setGeometry(QtCore.QRect(0, 170, 701, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        self.label_titulo_encuesta.setFont(font)
        self.label_titulo_encuesta.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_titulo_encuesta.setObjectName("label_titulo_encuesta")
        
        # Scroll
        
        self.scrollArea = QtWidgets.QScrollArea(MisEncuestas)
        self.scrollArea.setGeometry(QtCore.QRect(0, 220, 711, 651))
        self.scrollArea.setMinimumSize(QtCore.QSize(711, 651))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        
        self.scroll_widget= QtWidgets.QWidget()
        self.scrollArea.setWidget(self.scroll_widget)
        
        self.recargar_preguntas(datos)
        
        # Siguiente
        
        self.label_crear = QtWidgets.QLabel(MisEncuestas)
        self.label_crear.setGeometry(QtCore.QRect(0, 0, 511, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        self.label_crear.setFont(font)
        self.label_crear.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_crear.setObjectName("label_crear")
        
        self.btn_crear = QtWidgets.QPushButton(MisEncuestas)
        self.btn_crear.setGeometry(QtCore.QRect(440, 120, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_crear.setFont(font)
        self.btn_crear.setObjectName("btn_crear")
        
        self.line = QtWidgets.QFrame(MisEncuestas)
        self.line.setGeometry(QtCore.QRect(-3, 160, 711, 16))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        
        self.btn_eliminar = QtWidgets.QPushButton(MisEncuestas)
        self.btn_eliminar.setGeometry(QtCore.QRect(120, 120, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_eliminar.setFont(font)
        self.btn_eliminar.setObjectName("btn_eliminar")
        
        self.btn_publicar = QtWidgets.QPushButton(MisEncuestas)
        self.btn_publicar.setGeometry(QtCore.QRect(520, 13, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_publicar.setFont(font)
        self.btn_publicar.setObjectName("btn_publicar")
        
        self.line_2 = QtWidgets.QFrame(MisEncuestas)
        self.line_2.setGeometry(QtCore.QRect(0, 50, 711, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        
        self.btn_cambiar = QtWidgets.QPushButton(MisEncuestas)
        self.btn_cambiar.setGeometry(QtCore.QRect(570, 70, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_cambiar.setFont(font)
        self.btn_cambiar.setObjectName("btn_cambiar")
        
        self.label_titulo = QtWidgets.QLabel(MisEncuestas)
        self.label_titulo.setGeometry(QtCore.QRect(30, 70, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        self.label_titulo.setFont(font)
        self.label_titulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_titulo.setObjectName("label_titulo")
        
        self.label_numero = QtWidgets.QLabel(MisEncuestas)
        self.label_numero.setGeometry(QtCore.QRect(30, 120, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        self.label_numero.setFont(font)
        self.label_numero.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_numero.setObjectName("label_numero")
        
        self.txt_titulo = QtWidgets.QLineEdit(MisEncuestas)
        self.txt_titulo.setGeometry(QtCore.QRect(90, 70, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_titulo.setFont(font)
        self.txt_titulo.setObjectName("txt_titulo")
        
        self.txt_numero = QtWidgets.QLineEdit(MisEncuestas)
        self.txt_numero.setGeometry(QtCore.QRect(70, 120, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_numero.setFont(font)
        self.txt_numero.setObjectName("txt_numero")

        self.retranslateUi(MisEncuestas)
        QtCore.QMetaObject.connectSlotsByName(MisEncuestas)

    def recargar_preguntas(self, datos_preguntas: tuple[int, str, str, list[ tuple[int, str] | tuple[int, str, bool, list[tuple[int, str]]] ]]):
        
        self.scroll_widget.setParent(None)
        
        self.scroll_widget = QtWidgets.QWidget()
        self.scroll_widget.setGeometry(QtCore.QRect(0, 0, 709, 649))
        self.scroll_widget.setObjectName("scroll_widget")
        
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scroll_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        
        _translate = QtCore.QCoreApplication.translate
        if datos_preguntas is not None:
            self.label_titulo_encuesta.setText(_translate("MisEncuestas", datos_preguntas[1]))
        else:
            self.label_titulo_encuesta.setText(_translate("MisEncuestas", "Título"))
        
        if datos_preguntas is not None:
            for dato in datos_preguntas[3]:
                if len(dato) == 2:
                    # Group box texto
                    
                    group_box_texto = QtWidgets.QGroupBox(self.scroll_widget)
                    group_box_texto.setMinimumSize(QtCore.QSize(661, 145))
                    group_box_texto.setMaximumSize(QtCore.QSize(661, 145))
                    font = QtGui.QFont()
                    font.setPointSize(17)
                    group_box_texto.setFont(font)
                    group_box_texto.setObjectName("group_box_texto")
                    group_box_texto.setTitle(_translate("MisEncuestas", str(dato[0])))
                    
                    label_pregunta_texto = QtWidgets.QLabel(group_box_texto)
                    label_pregunta_texto.setGeometry(QtCore.QRect(10, 30, 631, 31))
                    font = QtGui.QFont()
                    font.setPointSize(16)
                    font.setBold(True)
                    label_pregunta_texto.setFont(font)
                    label_pregunta_texto.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
                    label_pregunta_texto.setObjectName("label_pregunta_texto")
                    label_pregunta_texto.setText(_translate("MisEncuestas", str(dato[1])))
                    
                    txt_texto = QtWidgets.QPlainTextEdit(group_box_texto)
                    txt_texto.setGeometry(QtCore.QRect(10, 70, 631, 61))
                    font = QtGui.QFont()
                    font.setPointSize(15)
                    txt_texto.setFont(font)
                    txt_texto.setObjectName("txt_texto")
                    
                    self.verticalLayout.addWidget(group_box_texto)
                
                else:
                    ## Group box om 
                    tam = 81
                    
                    opciones = dato[3]
                    
                    if opciones is not None:
                        if len(opciones) > 0:
                            tam += (len(opciones)*30)
                    
                    group_box_om = QtWidgets.QGroupBox(self.scroll_widget)
                    group_box_om.setMinimumSize(QtCore.QSize(661, tam))
                    group_box_om.setMaximumSize(QtCore.QSize(661, tam))
                    font = QtGui.QFont()
                    font.setPointSize(17)
                    group_box_om.setFont(font)
                    group_box_om.setObjectName("group_box_om")
                    group_box_om.setTitle(_translate("MisEncuestas", str(dato[0])))
                    
                    label_pregunta_om = QtWidgets.QLabel(group_box_om)
                    label_pregunta_om.setGeometry(QtCore.QRect(10, 30, 631, 31))
                    font = QtGui.QFont()
                    font.setPointSize(16)
                    font.setBold(True)
                    label_pregunta_om.setFont(font)
                    label_pregunta_om.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
                    label_pregunta_om.setObjectName("label_pregunta_om")
                    label_pregunta_om.setText(_translate("MisEncuestas", str(dato[1])))
                    
                    posy = 70
                    if opciones is not None:
                        for op in opciones:
                            if not dato[2]:
                                rdbtn_op = QtWidgets.QRadioButton(group_box_om)
                                rdbtn_op.setGeometry(QtCore.QRect(18, posy, 621, 31))
                                font = QtGui.QFont()
                                font.setPointSize(16)
                                rdbtn_op.setFont(font)
                                rdbtn_op.setObjectName("rdbtn_op")
                                rdbtn_op.setText(_translate("CrearPregunta", op[1]))
                            else:
                                ckb_op = QtWidgets.QCheckBox(group_box_om)
                                ckb_op.setGeometry(QtCore.QRect(18, posy, 621, 31))
                                ckb_op.setObjectName("ckb_op")
                                ckb_op.setText(_translate("CrearPregunta", op[1]))
                            posy += 30
                    
                    self.verticalLayout.addWidget(group_box_om)
        
        ## Agrega scroll_widget al scroll Area
        
        self.scrollArea.setWidget(self.scroll_widget)

    def retranslateUi(self, MisEncuestas):
        _translate = QtCore.QCoreApplication.translate
        MisEncuestas.setWindowTitle(_translate("MisEncuestas", "Crear Encuesta"))

        self.label_crear.setText(_translate("MisEncuestas", "Crear Encuesta"))
        self.btn_crear.setText(_translate("MisEncuestas", "Crear Pregunta"))
        
        self.btn_eliminar.setText(_translate("MisEncuestas", "Eliminar Pregunta"))
        self.btn_publicar.setText(_translate("MisEncuestas", "Publicar"))
        self.btn_cambiar.setText(_translate("MisEncuestas", "Cambiar"))
        self.label_titulo.setText(_translate("MisEncuestas", "Título:"))
        self.label_numero.setText(_translate("MisEncuestas", "Nº:"))
