# Form implementation generated from reading ui file 'CrearEncuesta.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CrearEncuesta(object):
    def setupUi(self, MisEncuestas):
        MisEncuestas.setObjectName("MisEncuestas")
        MisEncuestas.resize(708, 866)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/editar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        
        MisEncuestas.setWindowIcon(icon)
        
        self.scrollArea = QtWidgets.QScrollArea(MisEncuestas)
        self.scrollArea.setGeometry(QtCore.QRect(0, 220, 711, 651))
        self.scrollArea.setMinimumSize(QtCore.QSize(711, 651))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        
        self.scroll_widget = QtWidgets.QWidget()
        self.scroll_widget.setGeometry(QtCore.QRect(0, 0, 709, 649))
        self.scroll_widget.setObjectName("scroll_widget")
        
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scroll_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        
        # Group box texto
        
        self.group_box_texto = QtWidgets.QGroupBox(self.scroll_widget)
        self.group_box_texto.setMinimumSize(QtCore.QSize(661, 145))
        self.group_box_texto.setMaximumSize(QtCore.QSize(661, 145))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.group_box_texto.setFont(font)
        self.group_box_texto.setObjectName("group_box_texto")
        
        self.label_pregunta_texto = QtWidgets.QLabel(self.group_box_texto)
        self.label_pregunta_texto.setGeometry(QtCore.QRect(10, 30, 631, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_pregunta_texto.setFont(font)
        self.label_pregunta_texto.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_pregunta_texto.setObjectName("label_pregunta_texto")
        
        self.txt_texto = QtWidgets.QPlainTextEdit(self.group_box_texto)
        self.txt_texto.setGeometry(QtCore.QRect(10, 70, 631, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.txt_texto.setFont(font)
        self.txt_texto.setObjectName("txt_texto")
        
        self.verticalLayout.addWidget(self.group_box_texto)
        
        ## Group box om 
        
        self.group_box_om = QtWidgets.QGroupBox(self.scroll_widget)
        self.group_box_om.setMinimumSize(QtCore.QSize(661, 141))
        self.group_box_om.setMaximumSize(QtCore.QSize(661, 141))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.group_box_om.setFont(font)
        self.group_box_om.setObjectName("group_box_om")
        
        self.label_pregunta_om = QtWidgets.QLabel(self.group_box_om)
        self.label_pregunta_om.setGeometry(QtCore.QRect(10, 30, 631, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_pregunta_om.setFont(font)
        self.label_pregunta_om.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_pregunta_om.setObjectName("label_pregunta_om")
        
        self.rdbtn_op1 = QtWidgets.QRadioButton(self.group_box_om)
        self.rdbtn_op1.setGeometry(QtCore.QRect(20, 70, 621, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rdbtn_op1.setFont(font)
        self.rdbtn_op1.setObjectName("rdbtn_op1")
        
        self.rdbtn_op2 = QtWidgets.QRadioButton(self.group_box_om)
        self.rdbtn_op2.setGeometry(QtCore.QRect(20, 100, 621, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rdbtn_op2.setFont(font)
        self.rdbtn_op2.setObjectName("rdbtn_op2")
        
        self.verticalLayout.addWidget(self.group_box_om)
        
        ## Siguiente group vf
        
        self.group_box_vf = QtWidgets.QGroupBox(self.scroll_widget)
        self.group_box_vf.setMinimumSize(QtCore.QSize(661, 145))
        self.group_box_vf.setMaximumSize(QtCore.QSize(661, 145))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.group_box_vf.setFont(font)
        self.group_box_vf.setObjectName("group_box_vf")
        
        self.label_pregunta_vf = QtWidgets.QLabel(self.group_box_vf)
        self.label_pregunta_vf.setGeometry(QtCore.QRect(10, 30, 631, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_pregunta_vf.setFont(font)
        self.label_pregunta_vf.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_pregunta_vf.setObjectName("label_pregunta_vf")
        
        self.rdbtn_verdadero = QtWidgets.QRadioButton(self.group_box_vf)
        self.rdbtn_verdadero.setGeometry(QtCore.QRect(20, 70, 131, 31))
        self.rdbtn_verdadero.setObjectName("rdbtn_verdadero")
        
        self.btn_group = QtWidgets.QButtonGroup(MisEncuestas)
        self.btn_group.setObjectName("btn_group")
        self.btn_group.addButton(self.rdbtn_verdadero)
        
        self.rdbtn_falso = QtWidgets.QRadioButton(self.group_box_vf)
        self.rdbtn_falso.setGeometry(QtCore.QRect(20, 100, 81, 31))
        self.rdbtn_falso.setObjectName("rdbtn_falso")
        
        self.btn_group.addButton(self.rdbtn_falso)
        
        self.verticalLayout.addWidget(self.group_box_vf)
        
        self.scrollArea.setWidget(self.scroll_widget)
        
        # Siguiente
        
        self.label_crear = QtWidgets.QLabel(MisEncuestas)
        self.label_crear.setGeometry(QtCore.QRect(0, 0, 511, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        self.label_crear.setFont(font)
        self.label_crear.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_crear.setObjectName("label_crear")
        
        self.btn_crear = QtWidgets.QPushButton(MisEncuestas)
        self.btn_crear.setGeometry(QtCore.QRect(440, 120, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_crear.setFont(font)
        self.btn_crear.setObjectName("btn_crear")
        
        self.label_titulo_encuesta = QtWidgets.QLabel(MisEncuestas)
        self.label_titulo_encuesta.setGeometry(QtCore.QRect(0, 170, 701, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        self.label_titulo_encuesta.setFont(font)
        self.label_titulo_encuesta.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_titulo_encuesta.setObjectName("label_titulo_encuesta")
        
        self.line = QtWidgets.QFrame(MisEncuestas)
        self.line.setGeometry(QtCore.QRect(-3, 160, 711, 16))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        
        self.btn_eliminar = QtWidgets.QPushButton(MisEncuestas)
        self.btn_eliminar.setGeometry(QtCore.QRect(120, 120, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_eliminar.setFont(font)
        self.btn_eliminar.setObjectName("btn_eliminar")
        
        self.btn_publicar = QtWidgets.QPushButton(MisEncuestas)
        self.btn_publicar.setGeometry(QtCore.QRect(520, 13, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_publicar.setFont(font)
        self.btn_publicar.setObjectName("btn_publicar")
        
        self.line_2 = QtWidgets.QFrame(MisEncuestas)
        self.line_2.setGeometry(QtCore.QRect(0, 50, 711, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        
        self.btn_cambiar = QtWidgets.QPushButton(MisEncuestas)
        self.btn_cambiar.setGeometry(QtCore.QRect(570, 70, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_cambiar.setFont(font)
        self.btn_cambiar.setObjectName("btn_cambiar")
        
        self.label_titulo = QtWidgets.QLabel(MisEncuestas)
        self.label_titulo.setGeometry(QtCore.QRect(30, 70, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        self.label_titulo.setFont(font)
        self.label_titulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_titulo.setObjectName("label_titulo")
        
        self.label_numero = QtWidgets.QLabel(MisEncuestas)
        self.label_numero.setGeometry(QtCore.QRect(30, 120, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        self.label_numero.setFont(font)
        self.label_numero.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_numero.setObjectName("label_numero")
        
        self.txt_titulo = QtWidgets.QLineEdit(MisEncuestas)
        self.txt_titulo.setGeometry(QtCore.QRect(90, 70, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_titulo.setFont(font)
        self.txt_titulo.setObjectName("txt_titulo")
        
        self.txt_numero = QtWidgets.QLineEdit(MisEncuestas)
        self.txt_numero.setGeometry(QtCore.QRect(70, 120, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_numero.setFont(font)
        self.txt_numero.setObjectName("txt_numero")

        self.retranslateUi(MisEncuestas)
        QtCore.QMetaObject.connectSlotsByName(MisEncuestas)

    def imprimeGroup(self, scroll_area, vertical_layout, lista_group):
        pass

    def retranslateUi(self, MisEncuestas):
        _translate = QtCore.QCoreApplication.translate
        MisEncuestas.setWindowTitle(_translate("MisEncuestas", "Crear Encuesta"))
        self.group_box_texto.setTitle(_translate("MisEncuestas", "1"))
        self.label_pregunta_texto.setText(_translate("MisEncuestas", "Pregunta"))
        self.group_box_om.setTitle(_translate("MisEncuestas", "3"))
        self.label_pregunta_om.setText(_translate("MisEncuestas", "Pregunta"))
        self.rdbtn_op1.setText(_translate("MisEncuestas", "Opcion1"))
        self.rdbtn_op2.setText(_translate("MisEncuestas", "Opcion2"))
        self.group_box_vf.setTitle(_translate("MisEncuestas", "2"))
        self.label_pregunta_vf.setText(_translate("MisEncuestas", "Pregunta"))
        self.rdbtn_verdadero.setText(_translate("MisEncuestas", "Verdadero"))
        self.rdbtn_falso.setText(_translate("MisEncuestas", "Falso"))
        self.label_crear.setText(_translate("MisEncuestas", "Crear Encuesta"))
        self.btn_crear.setText(_translate("MisEncuestas", "Crear Pregunta"))
        self.label_titulo_encuesta.setText(_translate("MisEncuestas", "Título"))
        self.btn_eliminar.setText(_translate("MisEncuestas", "Eliminar Pregunta"))
        self.btn_publicar.setText(_translate("MisEncuestas", "Publicar"))
        self.btn_cambiar.setText(_translate("MisEncuestas", "Cambiar"))
        self.label_titulo.setText(_translate("MisEncuestas", "Título:"))
        self.label_numero.setText(_translate("MisEncuestas", "Nº:"))
