# Form implementation generated from reading ui file 'CrearPregunta.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CrearPregunta(object):
    def setupUi(self, CrearPregunta):
        CrearPregunta.setObjectName("CrearPregunta")
        CrearPregunta.resize(673, 420)
        font = QtGui.QFont()
        font.setPointSize(15)
        CrearPregunta.setFont(font)
        
        ## Tab Texto
        
        self.tab_texto = QtWidgets.QWidget()
        self.tab_texto.setObjectName("tab_texto")
        
        self.btn_cambiar_texto = QtWidgets.QPushButton(self.tab_texto)
        self.btn_cambiar_texto.setGeometry(QtCore.QRect(510, 30, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_cambiar_texto.setFont(font)
        self.btn_cambiar_texto.setObjectName("btn_cambiar_texto")
        
        self.txt_pregunta_texto = QtWidgets.QLineEdit(self.tab_texto)
        self.txt_pregunta_texto.setGeometry(QtCore.QRect(100, 30, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_pregunta_texto.setFont(font)
        self.txt_pregunta_texto.setObjectName("txt_pregunta_texto")
        
        self.label_pregunta_texto = QtWidgets.QLabel(self.tab_texto)
        self.label_pregunta_texto.setGeometry(QtCore.QRect(10, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        self.label_pregunta_texto.setFont(font)
        self.label_pregunta_texto.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_pregunta_texto.setObjectName("label_pregunta_texto")
        
        self.scroll_area_texto = QtWidgets.QScrollArea(self.tab_texto)
        self.scroll_area_texto.setGeometry(QtCore.QRect(-10, 100, 681, 211))
        self.scroll_area_texto.setWidgetResizable(True)
        self.scroll_area_texto.setObjectName("scroll_area_texto")
        
        self.scroll_widget_texto = QtWidgets.QWidget()
        self.scroll_widget_texto.setGeometry(QtCore.QRect(0, 0, 679, 209))
        self.scroll_widget_texto.setObjectName("scroll_widget_texto")
        
        self.txt_texto = QtWidgets.QPlainTextEdit(self.scroll_widget_texto)
        self.txt_texto.setGeometry(QtCore.QRect(20, 60, 631, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.txt_texto.setFont(font)
        self.txt_texto.setObjectName("txt_texto")
        
        self.label_pregunta_texto_box = QtWidgets.QLabel(self.scroll_widget_texto)
        self.label_pregunta_texto_box.setGeometry(QtCore.QRect(20, 20, 631, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_pregunta_texto_box.setFont(font)
        self.label_pregunta_texto_box.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_pregunta_texto_box.setObjectName("label_pregunta_texto_box")
        
        self.scroll_area_texto.setWidget(self.scroll_widget_texto)
        
        self.btn_agregar_texto = QtWidgets.QPushButton(self.tab_texto)
        self.btn_agregar_texto.setGeometry(QtCore.QRect(70, 340, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_agregar_texto.setFont(font)
        self.btn_agregar_texto.setObjectName("btn_agregar_texto")
        
        self.btn_limpiar_texto = QtWidgets.QPushButton(self.tab_texto)
        self.btn_limpiar_texto.setGeometry(QtCore.QRect(350, 340, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_limpiar_texto.setFont(font)
        self.btn_limpiar_texto.setObjectName("btn_limpiar_texto")
        
        self.label_prev_texto = QtWidgets.QLabel(self.tab_texto)
        self.label_prev_texto.setGeometry(QtCore.QRect(270, 70, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        self.label_prev_texto.setFont(font)
        self.label_prev_texto.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_prev_texto.setObjectName("label_prev_texto")
        
        CrearPregunta.addTab(self.tab_texto, "")
        
        ## Tab Verdadero Falso
        
        self.tab_vf = QtWidgets.QWidget()
        self.tab_vf.setObjectName("tab_vf")
        
        self.label_prev_vf = QtWidgets.QLabel(self.tab_vf)
        self.label_prev_vf.setGeometry(QtCore.QRect(270, 70, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        self.label_prev_vf.setFont(font)
        self.label_prev_vf.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_prev_vf.setObjectName("label_prev_vf")
        
        self.btn_limpiar_vf = QtWidgets.QPushButton(self.tab_vf)
        self.btn_limpiar_vf.setGeometry(QtCore.QRect(350, 340, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_limpiar_vf.setFont(font)
        self.btn_limpiar_vf.setObjectName("btn_limpiar_vf")
        
        self.label_pregunta_vf = QtWidgets.QLabel(self.tab_vf)
        self.label_pregunta_vf.setGeometry(QtCore.QRect(10, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        self.label_pregunta_vf.setFont(font)
        self.label_pregunta_vf.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_pregunta_vf.setObjectName("label_pregunta_vf")
        
        self.btn_agregar_vf = QtWidgets.QPushButton(self.tab_vf)
        self.btn_agregar_vf.setGeometry(QtCore.QRect(70, 340, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_agregar_vf.setFont(font)
        self.btn_agregar_vf.setObjectName("btn_agregar_vf")
        
        self.scroll_area_vf = QtWidgets.QScrollArea(self.tab_vf)
        self.scroll_area_vf.setGeometry(QtCore.QRect(-10, 100, 681, 211))
        self.scroll_area_vf.setWidgetResizable(True)
        self.scroll_area_vf.setObjectName("scroll_area_vf")
        
        self.scroll_widget_vf = QtWidgets.QWidget()
        self.scroll_widget_vf.setGeometry(QtCore.QRect(0, 0, 679, 209))
        self.scroll_widget_vf.setObjectName("scroll_widget_vf")
        
        self.rdbtn_verdadero = QtWidgets.QRadioButton(self.scroll_widget_vf)
        self.rdbtn_verdadero.setGeometry(QtCore.QRect(30, 50, 131, 31))
        self.rdbtn_verdadero.setObjectName("rdbtn_verdadero")
        
        self.rdbtn_falso = QtWidgets.QRadioButton(self.scroll_widget_vf)
        self.rdbtn_falso.setGeometry(QtCore.QRect(30, 80, 81, 31))
        self.rdbtn_falso.setObjectName("rdbtn_falso")
        
        self.label_pregunta_vf_box = QtWidgets.QLabel(self.scroll_widget_vf)
        self.label_pregunta_vf_box.setGeometry(QtCore.QRect(20, 20, 631, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_pregunta_vf_box.setFont(font)
        self.label_pregunta_vf_box.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_pregunta_vf_box.setObjectName("label_pregunta_vf_box")
        
        self.scroll_area_vf.setWidget(self.scroll_widget_vf)
        
        self.btn_cambiar_vf = QtWidgets.QPushButton(self.tab_vf)
        self.btn_cambiar_vf.setGeometry(QtCore.QRect(510, 30, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_cambiar_vf.setFont(font)
        self.btn_cambiar_vf.setObjectName("btn_cambiar_vf")
        
        self.txt_pregunta_vf = QtWidgets.QLineEdit(self.tab_vf)
        self.txt_pregunta_vf.setGeometry(QtCore.QRect(100, 30, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_pregunta_vf.setFont(font)
        self.txt_pregunta_vf.setObjectName("txt_pregunta_vf")
        
        CrearPregunta.addTab(self.tab_vf, "")
        
        ## Tab Opcion Multiple
        
        self.tab_om = QtWidgets.QWidget()
        self.tab_om.setObjectName("tab_om")
        
        self.btn_agregar_om = QtWidgets.QPushButton(self.tab_om)
        self.btn_agregar_om.setGeometry(QtCore.QRect(70, 340, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_agregar_om.setFont(font)
        self.btn_agregar_om.setObjectName("btn_agregar_om")
        
        self.scroll_area_om = QtWidgets.QScrollArea(self.tab_om)
        self.scroll_area_om.setGeometry(QtCore.QRect(-10, 130, 681, 201))
        self.scroll_area_om.setMinimumSize(QtCore.QSize(681, 201))
        self.scroll_area_om.setMaximumSize(QtCore.QSize(651, 201))
        self.scroll_area_om.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scroll_area_om.setWidgetResizable(True)
        self.scroll_area_om.setObjectName("scroll_area_om")
        
        self.scroll_widget_om= QtWidgets.QWidget()
        self.scroll_widget_om.setGeometry(QtCore.QRect(0, 0, 679, 199))
        self.scroll_widget_om.setObjectName("scroll_widget_om")
        
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scroll_widget_om)
        self.verticalLayout.setObjectName("verticalLayout")
        
        self.groupBox = QtWidgets.QGroupBox(self.scroll_widget_om)
        self.groupBox.setMinimumSize(QtCore.QSize(649, 159))
        self.groupBox.setMaximumSize(QtCore.QSize(649, 300))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        
        self.ckb_op3 = QtWidgets.QCheckBox(self.groupBox)
        self.ckb_op3.setGeometry(QtCore.QRect(18, 110, 621, 31))
        self.ckb_op3.setObjectName("ckb_op3")
        
        self.label_pregunta_om_box = QtWidgets.QLabel(self.groupBox)
        self.label_pregunta_om_box.setGeometry(QtCore.QRect(10, 10, 631, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_pregunta_om_box.setFont(font)
        self.label_pregunta_om_box.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_pregunta_om_box.setObjectName("label_pregunta_om_box")
        
        self.rdbtn_op2 = QtWidgets.QRadioButton(self.groupBox)
        self.rdbtn_op2.setGeometry(QtCore.QRect(18, 80, 621, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rdbtn_op2.setFont(font)
        self.rdbtn_op2.setObjectName("rdbtn_op2")
        
        self.rdbtn_op1 = QtWidgets.QRadioButton(self.groupBox)
        self.rdbtn_op1.setGeometry(QtCore.QRect(18, 50, 621, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rdbtn_op1.setFont(font)
        self.rdbtn_op1.setObjectName("rdbtn_op1")
        
        self.verticalLayout.addWidget(self.groupBox)
        self.scroll_area_om.setWidget(self.scroll_widget_om)
        
        self.label_pregunta_om = QtWidgets.QLabel(self.tab_om)
        self.label_pregunta_om.setGeometry(QtCore.QRect(10, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        self.label_pregunta_om.setFont(font)
        self.label_pregunta_om.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_pregunta_om.setObjectName("label_pregunta_om")
        
        self.txt_pregunta_om = QtWidgets.QLineEdit(self.tab_om)
        self.txt_pregunta_om.setGeometry(QtCore.QRect(100, 10, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_pregunta_om.setFont(font)
        self.txt_pregunta_om.setObjectName("txt_pregunta_om")
        
        self.label_prev_om = QtWidgets.QLabel(self.tab_om)
        self.label_prev_om.setGeometry(QtCore.QRect(270, 100, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        self.label_prev_om.setFont(font)
        self.label_prev_om.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_prev_om.setObjectName("label_prev_om")
        
        self.btn_cambiar_om = QtWidgets.QPushButton(self.tab_om)
        self.btn_cambiar_om.setGeometry(QtCore.QRect(510, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_cambiar_om.setFont(font)
        self.btn_cambiar_om.setObjectName("btn_cambiar_om")
        
        self.btn_limpiar_om = QtWidgets.QPushButton(self.tab_om)
        self.btn_limpiar_om.setGeometry(QtCore.QRect(350, 340, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_limpiar_om.setFont(font)
        self.btn_limpiar_om.setObjectName("btn_limpiar_om")
        
        self.label_opcion_om = QtWidgets.QLabel(self.tab_om)
        self.label_opcion_om.setGeometry(QtCore.QRect(10, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        self.label_opcion_om.setFont(font)
        self.label_opcion_om.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_opcion_om.setObjectName("label_opcion_om")
        
        self.txt_opcion_om = QtWidgets.QLineEdit(self.tab_om)
        self.txt_opcion_om.setGeometry(QtCore.QRect(100, 50, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_opcion_om.setFont(font)
        self.txt_opcion_om.setObjectName("txt_opcion_om")
        
        self.btn_agregarop_om = QtWidgets.QPushButton(self.tab_om)
        self.btn_agregarop_om.setGeometry(QtCore.QRect(510, 50, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_agregarop_om.setFont(font)
        self.btn_agregarop_om.setObjectName("btn_agregarop_om")
        
        self.ckb_varias = QtWidgets.QCheckBox(self.tab_om)
        self.ckb_varias.setGeometry(QtCore.QRect(480, 90, 161, 31))
        self.ckb_varias.setObjectName("ckb_varias")
        
        CrearPregunta.addTab(self.tab_om, "")

        self.retranslateUi(CrearPregunta)
        CrearPregunta.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CrearPregunta)

    def retranslateUi(self, CrearPregunta):
        _translate = QtCore.QCoreApplication.translate
        CrearPregunta.setWindowTitle(_translate("CrearPregunta", "Crear Pregunta"))
        self.btn_cambiar_texto.setText(_translate("CrearPregunta", "Cambiar"))
        self.label_pregunta_texto.setText(_translate("CrearPregunta", "Pregunta:"))
        self.label_pregunta_texto_box.setText(_translate("CrearPregunta", "Pregunta"))
        self.btn_agregar_texto.setText(_translate("CrearPregunta", "Agregar"))
        self.btn_limpiar_texto.setText(_translate("CrearPregunta", "Limpiar"))
        self.label_prev_texto.setText(_translate("CrearPregunta", "Previsualización"))
        CrearPregunta.setTabText(CrearPregunta.indexOf(self.tab_texto), _translate("CrearPregunta", "Texto"))
        self.label_prev_vf.setText(_translate("CrearPregunta", "Previsualización"))
        self.btn_limpiar_vf.setText(_translate("CrearPregunta", "Limpiar"))
        self.label_pregunta_vf.setText(_translate("CrearPregunta", "Pregunta:"))
        self.btn_agregar_vf.setText(_translate("CrearPregunta", "Agregar"))
        self.rdbtn_verdadero.setText(_translate("CrearPregunta", "Verdadero"))
        self.rdbtn_falso.setText(_translate("CrearPregunta", "Falso"))
        self.label_pregunta_vf_box.setText(_translate("CrearPregunta", "Pregunta"))
        self.btn_cambiar_vf.setText(_translate("CrearPregunta", "Cambiar"))
        CrearPregunta.setTabText(CrearPregunta.indexOf(self.tab_vf), _translate("CrearPregunta", "Verdadero y Falso"))
        self.btn_agregar_om.setText(_translate("CrearPregunta", "Agregar"))
        self.ckb_op3.setText(_translate("CrearPregunta", "Opcion3"))
        self.label_pregunta_om_box.setText(_translate("CrearPregunta", "Pregunta"))
        self.rdbtn_op2.setText(_translate("CrearPregunta", "Opcion2"))
        self.rdbtn_op1.setText(_translate("CrearPregunta", "Opcion1"))
        self.label_pregunta_om.setText(_translate("CrearPregunta", "Pregunta:"))
        self.label_prev_om.setText(_translate("CrearPregunta", "Previsualización"))
        self.btn_cambiar_om.setText(_translate("CrearPregunta", "Cambiar"))
        self.btn_limpiar_om.setText(_translate("CrearPregunta", "Limpiar"))
        self.label_opcion_om.setText(_translate("CrearPregunta", "Opción:"))
        self.btn_agregarop_om.setText(_translate("CrearPregunta", "Agregar"))
        self.ckb_varias.setText(_translate("CrearPregunta", "Varias Opciones"))
        CrearPregunta.setTabText(CrearPregunta.indexOf(self.tab_om), _translate("CrearPregunta", "Opción Multiple"))
