# Form implementation generated from reading ui file 'DialogoAC.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogoAC(object):
    def setupUi(self, DialogoAC):
        DialogoAC.setObjectName("DialogoAC")
        DialogoAC.resize(400, 233)
        DialogoAC.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/notificacion.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        DialogoAC.setWindowIcon(icon)
        DialogoAC.setStatusTip("")
        DialogoAC.setSizeGripEnabled(False)
        DialogoAC.setModal(False)
        self.btns = QtWidgets.QDialogButtonBox(DialogoAC)
        self.btns.setGeometry(QtCore.QRect(30, 190, 341, 32))
        self.btns.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.btns.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.btns.setObjectName("btns")
        self.label_image_info = QtWidgets.QLabel(DialogoAC)
        self.label_image_info.setEnabled(True)
        self.label_image_info.setGeometry(QtCore.QRect(20, 10, 81, 81))
        self.label_image_info.setAcceptDrops(False)
        self.label_image_info.setToolTip("")
        self.label_image_info.setStatusTip("")
        self.label_image_info.setAutoFillBackground(False)
        self.label_image_info.setText("")
        self.label_image_info.setPixmap(QtGui.QPixmap("icons/notificacion.png"))
        self.label_image_info.setScaledContents(True)
        self.label_image_info.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_image_info.setObjectName("label_image_info")
        self.label_titulo = QtWidgets.QLabel(DialogoAC)
        self.label_titulo.setGeometry(QtCore.QRect(130, 30, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        self.label_titulo.setFont(font)
        self.label_titulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        self.label_texto = QtWidgets.QLabel(DialogoAC)
        self.label_texto.setGeometry(QtCore.QRect(30, 110, 341, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_texto.setFont(font)
        self.label_texto.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_texto.setObjectName("label_texto")
        self.label_image_error = QtWidgets.QLabel(DialogoAC)
        self.label_image_error.setEnabled(True)
        self.label_image_error.setGeometry(QtCore.QRect(17, 7, 87, 87))
        self.label_image_error.setAcceptDrops(False)
        self.label_image_error.setToolTip("")
        self.label_image_error.setStatusTip("")
        self.label_image_error.setAutoFillBackground(False)
        self.label_image_error.setText("")
        self.label_image_error.setPixmap(QtGui.QPixmap("icons/pulgar-hacia-abajo.png"))
        self.label_image_error.setScaledContents(True)
        self.label_image_error.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_image_error.setObjectName("label_image_error")
        self.label_image_correcto = QtWidgets.QLabel(DialogoAC)
        self.label_image_correcto.setEnabled(True)
        self.label_image_correcto.setGeometry(QtCore.QRect(20, 10, 81, 81))
        self.label_image_correcto.setAcceptDrops(False)
        self.label_image_correcto.setToolTip("")
        self.label_image_correcto.setStatusTip("")
        self.label_image_correcto.setAutoFillBackground(False)
        self.label_image_correcto.setText("")
        self.label_image_correcto.setPixmap(QtGui.QPixmap("icons/pulgar-arriba.png"))
        self.label_image_correcto.setScaledContents(True)
        self.label_image_correcto.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_image_correcto.setObjectName("label_image_correcto")
        self.label_image_mas = QtWidgets.QLabel(DialogoAC)
        self.label_image_mas.setEnabled(True)
        self.label_image_mas.setGeometry(QtCore.QRect(20, 10, 81, 81))
        self.label_image_mas.setAcceptDrops(False)
        self.label_image_mas.setToolTip("")
        self.label_image_mas.setStatusTip("")
        self.label_image_mas.setAutoFillBackground(False)
        self.label_image_mas.setText("")
        self.label_image_mas.setPixmap(QtGui.QPixmap("icons/computacion-en-la-nube (1).png"))
        self.label_image_mas.setScaledContents(True)
        self.label_image_mas.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_image_mas.setObjectName("label_image_mas")
        self.line = QtWidgets.QFrame(DialogoAC)
        self.line.setGeometry(QtCore.QRect(10, 100, 381, 16))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.label_image_menos = QtWidgets.QLabel(DialogoAC)
        self.label_image_menos.setEnabled(True)
        self.label_image_menos.setGeometry(QtCore.QRect(20, 10, 81, 81))
        self.label_image_menos.setAcceptDrops(False)
        self.label_image_menos.setToolTip("")
        self.label_image_menos.setStatusTip("")
        self.label_image_menos.setAutoFillBackground(False)
        self.label_image_menos.setText("")
        self.label_image_menos.setPixmap(QtGui.QPixmap("icons/computacion-en-la-nube (2).png"))
        self.label_image_menos.setScaledContents(True)
        self.label_image_menos.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_image_menos.setObjectName("label_image_menos")

        self.retranslateUi(DialogoAC)
        self.btns.accepted.connect(DialogoAC.accept) # type: ignore
        self.btns.rejected.connect(DialogoAC.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogoAC)

    def retranslateUi(self, DialogoAC):
        _translate = QtCore.QCoreApplication.translate
        DialogoAC.setWindowTitle(_translate("DialogoAC", "Mensaje"))
        self.label_titulo.setText(_translate("DialogoAC", "Titulo"))
        self.label_texto.setText(_translate("DialogoAC", "Texto"))
    
    def dialog(self, titulo, mensaje, tipo=0, imagen=0):
        _translate = QtCore.QCoreApplication.translate
        self.label_titulo.setText(_translate("DialogoAC", titulo))
        self.label_texto.setText(_translate("DialogoAC", mensaje))
        
        if (tipo == 0):
            self.btns.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        else:
            self.btns.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        
        self.label_image_correcto.setVisible(False)
        self.label_image_error.setVisible(False)
        self.label_image_info.setVisible(False)
        self.label_image_mas.setVisible(False)
        self.label_image_menos.setVisible(False)
        
        match(imagen):
            case 0: self.label_image_info.setVisible(True)
            case 1: self.label_image_correcto.setVisible(True)
            case 2: self.label_image_error.setVisible(True)
            case 3: self.label_image_mas.setVisible(True)
            case 4: self.label_image_menos.setVisible(True)
