# Form implementation generated from reading ui file 'TodasEncuestas.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TodasEncuestas(object):
    def setupUi(self, TodasEncuestas, datos: list[tuple[str, str, str, str]], nombres: dict[str, str]):
        TodasEncuestas.setObjectName("TodasEncuestas")
        TodasEncuestas.resize(708, 739)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/aplicaciones.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        TodasEncuestas.setWindowIcon(icon)
        
        self.scrollArea = QtWidgets.QScrollArea(TodasEncuestas)
        self.scrollArea.setGeometry(QtCore.QRect(0, 205, 711, 541))
        self.scrollArea.setMinimumSize(QtCore.QSize(711, 471))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        
        self.scroll_widget = QtWidgets.QWidget()
        self.scroll_widget.setGeometry(QtCore.QRect(0, 0, 709, 539))
        self.scroll_widget.setObjectName("scroll_widget")
        
        # Datos
        #Agrega a scroll area
        
        self.scrollArea.setWidget(self.scroll_widget)
        
        self.lista_box = []
        self.recargar_encuesta(datos, nombres)
        
        ## Siguiente
        
        self.label_titulo = QtWidgets.QLabel(TodasEncuestas)
        self.label_titulo.setGeometry(QtCore.QRect(0, 10, 701, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        self.label_titulo.setFont(font)
        self.label_titulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        
        self.label_buscar = QtWidgets.QLabel(TodasEncuestas)
        self.label_buscar.setGeometry(QtCore.QRect(20, 70, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        self.label_buscar.setFont(font)
        self.label_buscar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_buscar.setObjectName("label_buscar")
        
        self.combo_box_usuarios = QtWidgets.QComboBox(TodasEncuestas)
        self.combo_box_usuarios.setGeometry(QtCore.QRect(250, 80, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.combo_box_usuarios.setFont(font)
        self.combo_box_usuarios.setObjectName("combo_box_usuarios")
        
        self.btn_buscar = QtWidgets.QPushButton(TodasEncuestas)
        self.btn_buscar.setGeometry(QtCore.QRect(590, 120, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_buscar.setFont(font)
        self.btn_buscar.setObjectName("btn_buscar")
        
        self.label_buscar_2 = QtWidgets.QLabel(TodasEncuestas)
        self.label_buscar_2.setGeometry(QtCore.QRect(24, 110, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        self.label_buscar_2.setFont(font)
        self.label_buscar_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_buscar_2.setObjectName("label_buscar_2")
        
        self.txt_nombre = QtWidgets.QLineEdit(TodasEncuestas)
        self.txt_nombre.setGeometry(QtCore.QRect(250, 120, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_nombre.setFont(font)
        self.txt_nombre.setObjectName("txt_nombre")
        
        self.ckb_activar = QtWidgets.QCheckBox(TodasEncuestas)
        self.ckb_activar.setGeometry(QtCore.QRect(510, 160, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ckb_activar.setFont(font)
        self.ckb_activar.setObjectName("ckb_activar")
        
        self.date_edit = QtWidgets.QDateEdit(TodasEncuestas)
        self.date_edit.setGeometry(QtCore.QRect(250, 160, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.date_edit.setFont(font)
        self.date_edit.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 1, 1), QtCore.QTime(23, 59, 59)))
        self.date_edit.setMaximumDate(QtCore.QDate(2024, 12, 31))
        self.date_edit.setMinimumDate(QtCore.QDate(2021, 1, 1))
        self.date_edit.setObjectName("date_edit")
        
        self.label_buscar_3 = QtWidgets.QLabel(TodasEncuestas)
        self.label_buscar_3.setGeometry(QtCore.QRect(10, 150, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        self.label_buscar_3.setFont(font)
        self.label_buscar_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_buscar_3.setObjectName("label_buscar_3")

        self.retranslateUi(TodasEncuestas)
        QtCore.QMetaObject.connectSlotsByName(TodasEncuestas)

    def recargar_encuesta(self, datos: list[tuple[str, str, str, str]], nombres: dict[str, str]):
        
        self.scroll_widget.setParent(None)
        self.lista_box = []
        
        self.scroll_widget = QtWidgets.QWidget()
        self.scroll_widget.setGeometry(QtCore.QRect(0, 0, 709, 539))
        self.scroll_widget.setObjectName("scroll_widget")
        
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scroll_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        
        _translate = QtCore.QCoreApplication.translate
        
        for dato in datos:
            
            group_box = QtWidgets.QGroupBox(self.scroll_widget)
            group_box.setMinimumSize(QtCore.QSize(661, 131))
            group_box.setMaximumSize(QtCore.QSize(661, 131))
            group_box.setTitle("")
            group_box.setObjectName("group_box")
            
            btn_responder = QtWidgets.QPushButton(group_box)
            btn_responder.setGeometry(QtCore.QRect(520, 80, 121, 31))
            font = QtGui.QFont()
            font.setPointSize(14)
            btn_responder.setFont(font)
            btn_responder.setObjectName("btn_responder")
            btn_responder.setCheckable(True)
            btn_responder.setText(_translate("TodasEncuestas", "Responder"))
            
            label_titulo_box = QtWidgets.QLabel(group_box)
            label_titulo_box.setGeometry(QtCore.QRect(10, 10, 71, 31))
            font = QtGui.QFont()
            font.setPointSize(16)
            font.setBold(True)
            label_titulo_box.setFont(font)
            label_titulo_box.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
            label_titulo_box.setObjectName("label_titulo_box")
            label_titulo_box.setText(_translate("TodasEncuestas", "Titulo:"))
            
            label_nombre_box = QtWidgets.QLabel(group_box)
            label_nombre_box.setGeometry(QtCore.QRect(15, 50, 491, 31))
            font = QtGui.QFont()
            font.setPointSize(15)
            font.setBold(False)
            label_nombre_box.setFont(font)
            label_nombre_box.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
            label_nombre_box.setObjectName("label_nombre_box")
            label_nombre_box.setText(_translate("TodasEncuestas", dato[1]))
            
            label_creadopor = QtWidgets.QLabel(group_box)
            label_creadopor.setGeometry(QtCore.QRect(14, 90, 111, 31))
            font = QtGui.QFont()
            font.setPointSize(13)
            font.setBold(False)
            label_creadopor.setFont(font)
            label_creadopor.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
            label_creadopor.setObjectName("label_creadopor")
            label_creadopor.setText(_translate("TodasEncuestas", "Creado por:"))
            
            label_usuario = QtWidgets.QLabel(group_box)
            label_usuario.setGeometry(QtCore.QRect(130, 90, 381, 31))
            font = QtGui.QFont()
            font.setPointSize(13)
            font.setBold(False)
            label_usuario.setFont(font)
            label_usuario.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
            label_usuario.setObjectName("label_usuario")
            label_usuario.setText(_translate("TodasEncuestas", nombres[dato[3]] ))
            
            label_fehca_box = QtWidgets.QLabel(group_box)
            label_fehca_box.setGeometry(QtCore.QRect(510, 10, 131, 31))
            font = QtGui.QFont()
            font.setPointSize(13)
            font.setBold(False)
            label_fehca_box.setFont(font)
            label_fehca_box.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
            label_fehca_box.setObjectName("label_fehca_box")
            label_fehca_box.setText(_translate("TodasEncuestas", dato[2][:10]))
            
            self.verticalLayout.addWidget(group_box)
            
            self.lista_box.append((dato[0],btn_responder))
        
        
        self.scrollArea.setWidget(self.scroll_widget)

    def retranslateUi(self, TodasEncuestas):
        _translate = QtCore.QCoreApplication.translate
        TodasEncuestas.setWindowTitle(_translate("TodasEncuestas", "Todas las Encuestas"))
        
        self.label_titulo.setText(_translate("TodasEncuestas", "Encuestas"))
        self.label_buscar.setText(_translate("TodasEncuestas", "Buscar por usuario:"))
        self.btn_buscar.setText(_translate("TodasEncuestas", "Buscar"))
        self.label_buscar_2.setText(_translate("TodasEncuestas", "Buscar por titulo:   "))
        self.ckb_activar.setText(_translate("TodasEncuestas", "Activar"))
        self.label_buscar_3.setText(_translate("TodasEncuestas", "Buscar por fecha:"))
